### ISSUE TITLE
noisy instances 

### ISSUE THREAD

**Issue by nazaretl** [google/bi-tempered-loss#14]
Hi,
thanks for sharing your implementation. Is it possible to identify the noisy instances (return the noisy IDs or the clean set)?

Thanks!

**Comment by eamid** [comment]
In the bi-tempered loss, we don't assume access to the clean labels and instead design a loss function that can handle "possible" noise in the data. This is done by restricting the loss of each example to be below a certain constant value. If your goal is to detect noisy examples in a dataset where you don't have access to clean labels, one possibility is to consider the low-loss approach: 
https://arxiv.org/pdf/2104.01493.pdf
https://arxiv.org/pdf/2111.05428.pdf (+ references therein) 

The noisy examples (because of their incorrect labels) usually have a higher loss compared to the clean examples (see Figure 1(b) in the first paper). You can use this information to guess which examples are possibly noisy.

**Comment by nazaretl** [comment]
many thanks for the explanation!
